### ISSUE TITLE
1.1 support

### ISSUE THREAD

**Issue by emipa606** [AaronCRobinson/SeasonalWeather#2]
Hi, I went ahead and updated this mod for RimWorld 1.1
If you want you can use the code to update your version?
[SeasonalWeather11.zip](https://github.com/AaronCRobinson/SeasonalWeather/files/4417106/SeasonalWeather11.zip)

**Comment by AaronCRobinson** [comment]
Is there a reason that you didn't do a clone and then submitted a pull request? I didn't know anyone still was enjoying this mod. I can look at doing the update in a day or two but would prefer a PR if I am going to incorporate your code. Were there any specific changes you made that might not be obvious? Or pretty straight forward.

**Comment by emipa606** [comment]
I got asked to update it by someone on Steam but I thought it was better if
you updated it on your end if possible.
Use it if you want, I dont actually use the mod so it makes no difference
to me. The code is pretty much the same, just updated the .net and
references. Didnt have the time to do a clone/pull sorry.

**Comment by AaronCRobinson** [comment]
I understand. I can do it here probably tonight depending on if anything else comes up. I can't update anything on Steam anymore though. I live in China and the steamcommunity is banned here. If you care, you can post it to steam after I update it. Let me know if you are interested. Thanks for the info.

**Comment by emipa606** [comment]
No problem, since I uploaded your expanded roofing I can upload this to!

**Comment by AaronCRobinson** [comment]
Great. Should be updated now.

https://github.com/AaronCRobinson/SeasonalWeather/releases/tag/v1.1.1

**Comment by emipa606** [comment]
Great, thanks!
Ill publish it to Steam now.
Btw, you shouldnt have the Harmony.dll included in the mod anymore. It
should be referenced in the About-file instead.
https://www.reddit.com/r/RimWorld/comments/fbnm45/harmony_the_full_story/

**Comment by AaronCRobinson** [comment]
Oh. I missed this mistake. Yes. I know about the change to Harmony. I can clean it up here tomorrow. Cheers.

**Comment by AaronCRobinson** [comment]
It should be fixed now. Thanks for your vigilance on catching mistakes like this. Cheers.
